
# # # # # # # # # # # # # # # #		Makefile#	 # # # # # # # # # # # # # # # # #

# Flags used
# -g --Enable debugging
# -Wall --Turns on warnings
# -std=c++11 --Compiles with the c++ 11 version

CXX = g++
CXXFLAGS=-g -std=c++11 -Wall

#Link command:
Equitation_display: main.o eq_display.o 
	$(CXX) main.o eq_display.o -o Equitation_display


#make clean
clean:
	rm -rf *.o threadss
